[package]
name = "rustcgi-directory-server"
version = "0.1.0"
authors = ["Avi Weinstock <aweinstock314@gmail.com>"]
edition = "2018"

[dependencies]
warp = "0.2"

[build-dependencies]
bindgen = "0.53"
